AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template Dashboards
Parameters: 
  StackName:
    Description: Name of an active CloudFormation stack that contains the networking resources, such as the subnet and security group, that will be used in this stack
    Type: String
    MinLength : 1
    MaxLength : 255
    AllowedPattern : ^[a-zA-Z][-a-zA-Z0-9]*$
    Default : dad
    #default is the name of the bigger stack being referenced. 
Resources:
  CloudWatchDashboard:
   Type: "AWS::CloudWatch::Dashboard"
   Properties:
     DashboardName: HOSTNAME
     DashboardBody: !Join [ "", ['{"widgets":[
         {
           "type":"metric",
           "properties":{
             "metrics":[
               ["AWS/EC2","CPUUtilization","InstanceId",
                "', Fn::ImportValue:
                      !Sub "${StackName}-InstanceID", '"]
             ],
             "title":"CPU Utilization",
             "period":60,
             "region":"us-east-1"
           }
         }]}' ] ]



#Fn::ImportValue:
#  !Sub "${NetworkStack}-SubnetID"
#this is good

#!ImportValue sharedValueToImport