AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ResourceBucket:
    Type: String
    Description: S3Bucket where resources are stored.
  FileName:
    Type: String
    Description: FileName of file containing environment variables
  KeyPair:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Enter a valid KeyPair Name

Mappings:
  RegionToImageId:
    'ap-south-1':
      ImageId: 'ami-d783a9b8'
    'eu-west-3':
      ImageId: 'ami-2cf54551'
    'eu-west-2':
      ImageId: 'ami-b8b45ddf'
    'eu-west-1':
      ImageId: 'ami-466768ac'
    'ap-northeast-2':
      ImageId: 'ami-afd86dc1'
    'ap-northeast-1':
      ImageId: 'ami-e99f4896'
    'sa-east-1':
      ImageId: 'ami-6dca9001'
    'ca-central-1':
      ImageId: 'ami-0ee86a6a'
    'ap-southeast-1':
      ImageId: 'ami-05868579'
    'ap-southeast-2':
      ImageId: 'ami-39f8215b'
    'eu-central-1':
      ImageId: 'ami-7c4f7097'
    'us-east-1':
      ImageId: 'ami-0fecdd48f46904f51'
    'us-east-2':
      ImageId: 'ami-8c122be9'
    'us-west-1':
      ImageId: 'ami-e0ba5c83'
    'us-west-2':
      ImageId: 'ami-a9d09ed1'

Resources:
  OracleClient:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionToImageId, !Ref 'AWS::Region', ImageId]
      InstanceType: t2.micro
      KeyName: 
        Ref: KeyPair
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !ImportValue "PublicSubnetId"
          GroupSet:
            - !ImportValue WebAppSecurityGroupId
      UserData:
        Fn::Base64:
          !Sub
          - |
            #!/bin/bash
            sudo su
            cd ~
            wget ${Bucket}
            chmod 760 ${File}
            cat ${File} >> /etc/environment
            source /etc/environment
            cat ${File} >> /usr/share/tomcat/conf/tomcat.conf
            source /usr/share/tomcat/conf/tomcat.conf
            yum -y install git
            wget https://s3.amazonaws.com/buckywucky/Project2Auto.xml
            service tomcat start
            yum install -y amazon-efs-utils
            mkdir shared
            echo "${EFSId}:/ /root/shared efs defaults,_netdev 0 0" >> /etc/fstab
            mount -t efs ${EFSId}:/ shared
            sleep 60
            cat Project2Auto.xml | java -jar jenkins-cli.jar -s http://localhost:8080/jenkins/ -auth admin:admin create-job AutoProd2
            java -jar jenkins-cli.jar -s http://localhost:8080/jenkins/ -auth admin:admin build AutoProd2
            java -jar jenkins-cli.jar -s http://localhost:8080/jenkins/ -auth admin:admin build AutoProd2
            sleep 65
            echo "* * * * * cp -a /usr/share/tomcat/webapps/ERS.war shared/ " >> testCron
            crontab testCron
          - {
            Bucket: !Join [ "", [ "https://s3.amazonaws.com/", !Ref ResourceBucket, "/", !Ref FileName ] ],
            File: !Ref FileName,
            EFSId: !ImportValue "EFSId"
            }

Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref OracleClient
    Export:
      Name: "EC2ID"
